---
layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Joachim Schöpfel"
- "Hélène Prost"
title: "Research data management in social sciences and humanities: A survey at the University of Lille (France)"
urn: "urn:nbn:de:kobv:11-100238193"
abstract: "The paper presents results from a campus-wide survey at the University
of Lille (France) on research data management in social sciences and
humanities. The survey received 270 responses, equivalent to 15% of the
whole sample of scientists, scholars, PhD students, administrative and
technical staff (research management, technical support services); all
disciplines were represented. The responses show a wide variety of
practice and usage. The results are discussed regarding job status and
disciplines and compared to other surveys. Four groups can be
distinguished, i.e. pioneers (20-25%), motivated (25-30%), unaware (30%)
and reluctant (5-10%). Finally, the next steps to improve the research
data management on the campus are presented.<br>
Der Artikel stellt die Ergebnisse einer campusweiten Umfrage an der
Universität Lille (Frankreich) über den Umgang mit Forschungsdaten in
den Sozial- und Geisteswissenschaften vor. Die Umfrage hatte einen
Rücklauf von 270 Antworten, was 15% der gesamten Stichprobe von
Wissenschaftlern, Lehrkräften, Doktoranden, administrativen und
technischen Personal (Forschungsmanagement, technische Dienste)
entspricht; alle Disziplinen sind vertreten. Die Antworten zeigen eine
große Vielfalt an Praxis und Nutzung. Die Ergebnisse werden in Bezug auf
Berufsstatus und Disziplinen diskutiert und mit anderen Erhebungen
verglichen. Vier Gruppen können unterschieden werden: Vorläufer
(20-25%), Motivierte (25-30%), Unwissende (30%) und Zurückhaltende
(5-10%). Schließlich werden die nächsten Schritte vorgestellt, um das
Forschungsdatenmanagement auf dem Campus zu verbessern."
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
