---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Kevin Dubout"
title: "Durch Rezensionen zur Emanzipation? Die <q>Bibliographie der
Homosexualität</q> (1900-1922) im <i>Jahrbuch für sexuelle Zwischenstufen</i>"
date: 2016-06-16 13:00
urn : "urn:nbn:de:kobv:11-100238160"
comments: false
sharing: true
footer: true

---