
---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Adrian Pohl"
- "Fabian Steeg"
title: "Zurück ins Web. Die Entwicklung eines neuen Webauftritts für die Nordrhein-Westfälische Bibliographie (NWBib)"
date: 
abstract: ""
comments: false
sharing: true
footer: true

---