---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Manfred Herzer"
title: "Kurze Geschichte der Numa-Forschung"
urn: "urn:nbn:de:kobv:11-100238171"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
