---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Jakob Voß"
title: "Wikidata als Universalbibliographie: ein Kommentar"
abstract: "Der Kommentar weist auf die Bedeutung von Wikidata für die Entwicklung einer Universalbibliographie hin."
urn: "urn:nbn:de:kobv:11-100238121"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
