---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Krisztof Ján Kojakeva"
title: "Bibliographien: Einsichten eines ihrer möglichen Leser - ein Rundgang"
urn: "urn:nbn:de:kobv:11-100238139"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
