---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Tabea Bader"
title: "Open-Access-Repositorien in der Schweiz und Österreich -Auswertung des <i>2014 Census on Open Access Repositories</i>"
date: 2016-06-16 13:00
urn : "urn:nbn:de:kobv:11-100238925"
abstract: "Open-Access-Repositorien und werden in der wissenschaftlichen
Kommunikation immer wichtiger. Der <q>2014 Census on Open Access
Repositories in Germany, Austria and Switzerland</q> (Census 2014)
beschäftigte sich mit der Landschaft der Open-Access-Repositorien (OAR)
in den drei deutschsprachigen Ländern. In Bezug auf Deutschland wurden
die Daten bereits umfassend ausgewertet. Dieser Artikel gibt einen
Überblick über die Situation der Open-Access-Repositorien in der Schweiz
und Österreich auf Basis des Census 2014. Die Daten des Census werden
anhand der Kriterien Größe, Metadatenqualität, verwendete Software,
Rolle der Berliner Erklärung, Langzeitarchivierung,
Lizenzierungsmöglichkeiten unter anderem analysiert.
<br>
Bei den Auswertungen zeigte sich beispielsweise, dass Österreich und die
Schweiz wenige, aber dafür vergleichsweise große OAR haben. Die meisten
OAR verteilen sich auf Universitäten und außeruniversitäre
Forschungseinrichtungen. Fachhochschulrepositorien gibt es kaum, obwohl
es in beiden Ländern in etwa so viele Fachhochschulen wie Universitäten
gibt. Die Konformität der Metadaten mit den Vorgaben des
DINI-Zertifikats 2010 ist eher gering, jedoch muss beachtet werden, dass
kein OAR in den Alpenstaaten überhaupt ein Zertifikat besitzt. Weiterhin
lässt sich festhalten, dass die Software-Lösung EPrints dominiert."
abstractalt: "Open access repositories become more and more important in scholarly
research. The <q>2014 Census on Open Access Repositories in Germany,
Austria and Switzerland</q> investigated the landscape of Open Access
Repositories (OAR) in the three German speaking countries. In relation
to Germany the data has been analyzed already. This article gives an
overview of the situation of Open Access Repositories in Switzerland and
Austria.
<br>
The Census data are surveyed regarding the criteria size, metadata
quality, software used, the role of the Berlin Declaration, long term
archiving, licensing options and others.
<br>
The findings were amongst others that Austria and Switzerland have few
but big repositories. Most OAR are connected to universities and
non-university research institutions. Repositories at universities of
applied sciences are nearly non-existent although there are almost as
much universities of applied sciences as there are universities in both
countries. Conformity with the DINI metadata standards is low, but one
has to keep in mind that no OAR of the alpine states has a
DINI-certificate. Furthermore the analysis shows that the software
EPrints dominates."
comments: false
sharing: true
footer: true

---