---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Najko Jahn"
title: "Rezension zu: Pomerantz, Jeffrey. Metadata. The MIT Press Essential Knowledge Series. The MIT Press, 2015. ISBN: 978-0-262-52851-1. $15,95"
urn: "urn:nbn:de:kobv:11-100238209"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
